global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'inference-prod'
    static_configs:
      - targets: ['infer-prod:6001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'inference-candidate'
    static_configs:
      - targets: ['infer-cand:6002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']