name: Deploy MLOps to EC2

on:
  push:
    branches: [testing]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install test dependencies
        run: |
          pip install -r tests/requirements-test.txt
      
      - name: Run unit tests
        run: |
          python -m pytest tests/unit/ -v

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy MLOps Stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Expand root partition to use full EBS volume
            sudo growpart /dev/nvme0n1 1
            sudo resize2fs /dev/nvme0n1p1
            
            # Clean up Docker to free space
            docker system prune -af --volumes
            
            # Clone or update repository
            if [ -d "airflow" ]; then
              cd airflow
              git pull origin main
            else
              git clone https://github.com/ignatus-anim/mlops.git airflow
              cd airflow
            fi
            
            # Create .env file from secrets
            cat > .env << 'EOF'
            ${{ secrets.ENV_FILE }}
            EOF
            
            # Stop existing containers
            docker compose down || true
            
            # Start core services
            docker compose up -d
            
            # Deploy A/B testing
            docker compose -f docker-compose.ab.yml up -d --build router
            
            # Deploy monitoring
            docker compose -f monitoring/docker-compose.monitoring.yml up -d