name: Deploy MLOps to EC2

on:
  push:
    branches: [testing]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clone or update repository
            if [ -d "airflow" ]; then
              cd airflow
              git pull origin main
            else
              git clone https://github.com/ignatus-anim/mlops.git airflow
              cd airflow
            fi
            
            # Stop existing containers
            docker compose down || true
            
            # Start core services
            docker compose up -d
            
            # Deploy A/B testing router
            docker compose -f docker-compose.ab.yml up -d --build router
            
            # Deploy monitoring stack
            docker compose -f monitoring/docker-compose.monitoring.yml up -d