name: Deploy MLOps to EC2

on:
  push:
    branches: [testing]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install test dependencies
        run: |
          pip install -r tests/requirements-test.txt
      
      - name: Run unit tests
        run: |
          python -m pytest tests/unit/ -v

  deploy-core:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Core Services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Clone or update repository
            if [ -d "airflow" ]; then
              cd airflow
              git pull origin main
            else
              git clone https://github.com/ignatus-anim/mlops.git airflow
              cd airflow
            fi
            
            # Create .env file from secrets
            cat > .env << 'EOF'
            ${{ secrets.ENV_FILE }}
            EOF
            
            # Stop existing containers
            docker compose down || true
            
            # Start core services
            docker compose up -d

  deploy-ab:
    runs-on: ubuntu-latest
    needs: deploy-core
    steps:
      - name: Deploy A/B Testing
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd airflow
            docker compose -f docker-compose.ab.yml up -d --build router

  deploy-monitoring:
    runs-on: ubuntu-latest
    needs: deploy-ab
    steps:
      - name: Deploy Monitoring
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd airflow
            docker compose -f monitoring/docker-compose.monitoring.yml up -d